name: Laravel

on:
  push:
    branches: [ "main" , "staging" ]
  pull_request:
    branches: [ "main" , "staging" ]
jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: cd src && php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: cd src && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#     - name: migration
#       run: cd src && php artisan migrate
    - name: Generate key
      run: cd src && php artisan key:generate
    - name: Directory Permissions
      run: cd src && chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        cd src && mkdir -p database
        touch database/database.sqlite
#     - name: Execute tests (Unit and Feature tests) via PHPUnit
#       env:
#         DB_CONNECTION: sqlite
#         DB_DATABASE: database/database.sqlite
#       run: cd src && vendor/bin/phpunit
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [laravel-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.FTP_SAKURA_USERNAME }}
          HOST_NAME: ${{ secrets.FTP_SAKURA_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          if: github.ref == 'refs/heads/staging'
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${USER_NAME}@${HOST_NAME} 'cd /home/goldokapi5/staging/tenjin-renewal/ && git pull origin staging'
          if: github.ref == 'refs/heads/main'
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${USER_NAME}@${HOST_NAME} 'cd /home/goldokapi5/staging/tenjin-renewal/ && git pull origin main'


